### ISSUE TITLE
disable solidity optimization

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#131]
**Describe the bug**
solidity optimizer can have bugs and adds an extra layer of the attack surface.
such bugs have been reported before https://blog.ethereum.org/2017/05/03/solidity-optimizer-bug/

Disable the optimization in hardhat/equivalent to resolve.

**Comment by dev1644** [comment]
I think this issue should be closed because the [bug](https://blog.ethereum.org/2017/05/03/solidity-optimizer-bug/) mentioned is already fixed & does not affect `> 0.4.x` compilers.
Moreover, the bug was not found at any deployed contract at the time when it was published.
The compiler optimizer should remain on because it optimizes bytecode to reduce code size & execution cost.

The general rule of thumb -: If the interaction with the contract is gonna be limited (e.g. lottery contract etc.), then the optimizer should be off as it will help in relatively cheap deployment of the contract. But if a contract interacts frequently then an optimizer should be enabled as it will increase the deployment cost but later interactions with the contract will be cheaper.

There are also prominent projects on Ethereum that uses optimizer.
- https://github.com/Uniswap/uniswap-v2-core/blob/master/.waffle.json
- https://github.com/Uniswap/uniswap-v3-core/blob/main/hardhat.config.ts#L37
- https://github.com/sushiswap/sushiswap/blob/master/hardhat.config.ts#L279


Refs - https://docs.soliditylang.org/en/latest/internals/optimizer.html
