### ISSUE TITLE
upgrade compiler version to 0.8.4

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#132]
**Is your feature request related to a problem? Please describe.**
hardhat config uses 0.8.0. Current stable solidity version is 0.8.4
**Describe the solution you'd like**
use 0.8.4 compiler version in hardhat config and if required, in ci config

**Comment by dev1644** [comment]
I think the issue should be closed because the bug mentioned is already fixed & does not affect `> 0.4.x` compilers.
Moreover, the bug was not even found at any deployed contract at the time when it was published.
The compiler optimizer should remain on because it optimizes bytecode to cost less gas cost when interacting with it.

The general rule of thumb -: If the interaction with the contract is gonna be limited (e.g. lottery contract etc.), then the optimizer should be off as it will help in relatively cheap deployment of the contract. But if a contract interacts frequently then an optimizer should be enabled as it will increase the deployment cost but later interactions with the contract will be cheaper.

There are also prominent projects on Ethereum that uses optimizer.
- https://github.com/Uniswap/uniswap-v2-core/blob/master/.waffle.json
- https://github.com/Uniswap/uniswap-v3-core/blob/main/hardhat.config.ts#L37
- https://github.com/sushiswap/sushiswap/blob/master/hardhat.config.ts#L279
