### ISSUE TITLE
Write a functionality to choose if staker can propose a block if its stake is below min stake.

### ISSUE THREAD

**Issue by adi44** [razor-network/contracts#171]
**Describe the bug**
Currently staker is chosen using probabilistic method using peasudorandom funcion. But in case if stake is below minimum stake there is no method defined to choose a staker. 

Solution Proposed : Staker tosses a bias coin, where bias = minStake/biggestStake. if its head, staker can propose a block else wait for next iteration. 
https://github.com/razor-network/contracts/blob/1b9fcc1e6204f5a47c69cc1a0929bc7519a1e85b/contracts/Core/BlockManager.sol#L124-L130

**Comment by SkandaBhat** [comment]
This issue is already taken care of. We need to make a modification where we check for stake > minStake.

**Comment by SkandaBhat** [comment]
Issue is too ambiguous. Need better title and description. @adi44

**Comment by adi44** [comment]
https://github.com/razor-network/contracts/blob/1b9fcc1e6204f5a47c69cc1a0929bc7519a1e85b/contracts/Core/BlockManager.sol#L124-L130

**Comment by SkandaBhat** [comment]
@hrishikeshio is there any specific reason this is zero and not minStake?

https://github.com/razor-network/contracts/blob/1b9fcc1e6204f5a47c69cc1a0929bc7519a1e85b/contracts/Core/VoteManager.sol#L90

**Comment by hrishikeshio** [comment]
> @hrishikeshio is there any specific reason this is zero and not minStake?
> 
> https://github.com/razor-network/contracts/blob/1b9fcc1e6204f5a47c69cc1a0929bc7519a1e85b/contracts/Core/VoteManager.sol#L90

I guess it makes sense in the following scenario:

1. staker commits
2. stakers gets slashed due to his commit being revealed by someone else.
3. stakers stake drops below min stake but still above 0.
4. staker should still reveal to avoid further penalties (inactivity penalty)

would suggest opening a separate issue for that and analyze further.

I am closing this issue as the description and title still don't make sense.
