### ISSUE TITLE
Fix security issues reported by mythx

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#250]
build is currently failing due to security issues reported by mythx

**Comment by SkandaBhat** [comment]
https://swcregistry.io/docs/SWC-123

**Comment by adi44** [comment]
@SkandaBhat Can I take up this issue?

**Comment by hrishikeshio** [comment]
> @SkandaBhat Can I take up this issue?

yes

**Comment by adi44** [comment]
SWC-123 warnings say that the require statement should be in the current function where it needed to be checked. And the require statement should be true always, which means it should not be violated.
Coming to warnings that says that we should add the visibility of constructor, from solidity versions after 0.7.0, the visibility for constructor plays no role. Also since the constructor is called during the deployment only, it does not need to have any visibility.

**Comment by hrishikeshio** [comment]
@adi44 any update?

**Comment by adi44** [comment]
> @adi44 any update?

Yes, currently there are two warnings that is related to swc-123. It says that requirement violation can be there. So as per the link the cause of this warning can be either wrong input from external contract that does not statisfy require statement and other is too strong condition. I think either we can check require in everyfunction instead of modifier or else keep as it is
https://githubmemory.com/repo/SmartContractSecurity/SWC-registry/issues/119

**Comment by hrishikeshio** [comment]
ignore it

**Comment by SkandaBhat** [comment]
Closing this one as Mythx isnt working out for us.
