### ISSUE TITLE
staker can avoid inactivity penatly

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#284]
**Describe the bug**
inactivity penalty is applied in commit() based on current stake

staker can remain inactive for long time and then withdraw the funds before committing to avoid inactivity penalty.

**Expected behavior**
perhaps we need to apply inactivity penalty during withdraw as well.

**Comment by GauravJain9** [comment]
I had the same doubt while writing test I think initially withdraw function was calling penalties also

**Comment by hrishikeshio** [comment]
Yes i think it was there before and got removed in delegation pr @abhishekvispute

**Comment by abhishekvispute** [comment]
Hi Guys,
This was removed in this PR: https://github.com/razor-network/contracts/pull/79 : Withdraw Lock Improvement
We removed this because, in this PR, we are making it mandatory for staker to not participate in the network in the withdraw lock period. so we can avoid hit and run 
If we would have had this in withdraw, then staker would have been penalized for inactivity penalties as well as voting penalties
Please refer to this discussion: https://github.com/razor-network/contracts/pull/79#discussion_r594269985

But above case is correct, somehow we missed this.

**Comment by abhishekvispute** [comment]
One way we can solve this is by applying penalities in unstake 
Up to unstake staker is bound to participate

**Comment by SamAg19** [comment]
> One way we can solve this is by applying penalities in unstake
> Up to unstake staker is bound to participate

Yes, this seems like a good enough solution for this bug. Should i pick this up?

**Comment by SamAg19** [comment]
Will need to add a variable to the staker struct to keep track when the staker was penalised for inactivity. Otherwise the staker will be penalized unknowingly twice for inactivity

**Comment by hrishikeshio** [comment]
> Will need to add a variable to the staker struct to keep track when the staker was penalised for inactivity. Otherwise the staker will be penalized unknowingly twice for inactivity

please try to find a solution where this is not required. we shouldn't try to fix every issue by adding new variables.

**Comment by GauravJain9** [comment]
I thinkv we need to add givepenalties in withdraw  as 

entry point in network : commit => givepenalties is already present 
exit point => 'withdraw'

I think we can't add givepenalties in unstake because 
1) Suppose if staker was active till 10 epochs and in 11th epoch instead of commiting staker calls unstake and then suppose suffers from voting penalties and then staker remains inactive for any reason for much more epoch than "withdraw_lock_period" then calls resetlock (suffers from penalty of reset lock) and then unstake then in this case again staker will suffer from same voting penalties  (which was already given when staker called unstake the very 1st time )   +   inactivity penalties also.
Here voting penalty is being applied twice.


Adding "givepenalties" in withdraw : 
 1) If we add givepenalties in withdraw then if staker remains inactive then if he decides to participate then he will suffer all penalties (inactivity + voting) in commit 
and if he tries to run out after being inactive for many more epochs tham grace period then in that case staker will suffer penalties in withdraw (voting + inactivity) only once so staker can unstake as many times as he wants then if he tries to participate then in commit only he will be penalized or if wants to run away then in withdraw he will be penalized that also only once for each inactivity and voting.

**Comment by hrishikeshio** [comment]
problem 



- can bypass inactivity penalty 
  -unstake() and withdraw() after inactivity since we are not checking inactivity there

- after partial unstaking staker still cant participate 
  - after returning after lock period he will get inactivity penalty


solution 1

- unstake() convert unstaked srzr to rzr and reduce from stake; add to lock 10000
- withdraw() allow locked rzr to withdraw

**Comment by hrishikeshio** [comment]
thisStaker.epochFirstStaked  -> rename to thisStaker.epochLastUnstakedOrFirstStaked
