### ISSUE TITLE
Remove activity status from job

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#449]
- Remove activity status from job.
- If we are removing the last job in the collection, disable collection automatically.

**Comment by SamAg19** [comment]
If all jobs are deactivated, the collection becomes redundant but stakers will have to report some value as it would still considered as an active asset unless deactivated manually. Therefore, we'll have to deactivate it manually.
To do it automatically, we may need to create a mapping between the jobs and collections it is being used in because as of right now, a collection knows how many jobs it has but a job doesn't know which collection is belongs in. With this mapping, the job which is being deactivated can be removed from all the collections it was being used in and if the collection has no jobs after the removal, the collection can be then deactivated.

**Comment by abhishekvispute** [comment]
IMO activity status for job itself is not needed.
If job is redundant we can directly remove it from collection.
Why we need option to deactivate it.

Earlier it was needed as job had individual asset status
Now if there are only collection, why do we need to have activity status on job which are supposed to only store urls.

**Comment by SamAg19** [comment]
The only thing with that is we will have to manually remove the job from all the collections it is present in whereas by deactivating the job itself, stakers will not need to take the value of this job in consideration at the time of aggregation calculation of all the collections it is being used in as such a functionality can be handled on the client side

**Comment by adi44** [comment]
Picking this up @SkandaBhat
