### ISSUE TITLE
Slashing the block proposer if they propose incorrect biggestinfluenceID

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#474]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hrishikeshio** [comment]
Is this really an issue?
What is the potential attack? @abhishekvispute

**Comment by abhishekvispute** [comment]
hmm, yes there is attack vector 
we are not reverting for smaller influence, 
so if the block with better itr is proposed with smaller influence, it will be added first on basis of itr.
and if no block is proposed after it to replace it, it stays as chosen block to be confirmed.
that's why we need option to dispute it.

CC : @hrishikeshio

**Comment by hrishikeshio** [comment]
maybe better to track biggest influence in the epoch and compare/update it on every propose. wont consume alot of gas. and less disrputive/risky.

maybe here https://github.com/razor-network/contracts/pull/483/files#diff-ef39b70abd99dba15254b650eeab6fe94780b7804fbd0715169e10e8ad67e198R70

**Comment by abhishekvispute** [comment]
yes, agree, we can do so, shall we do it current pending pr only,
Its a small addition
