### ISSUE TITLE
Add tolerance 

### ISSUE THREAD

**Issue by hrishikeshio** [razor-network/contracts#601]
tolerate x% of deviation from aggregate and dont give any penalty, here x is a governance parameter.
Set default to 2%.
Ref #592

**Comment by SkandaBhat** [comment]
- [ ] Implement tolerance for each job

**Comment by SamAg19** [comment]
There may be an issue with assetIndex in voteManager function `getVoteValue`
https://github.com/razor-network/contracts/blob/e640fb64721d91280b532e4efced7e4c98ff10e8/contracts/Core/VoteManager.sol#L111

suppose activeCollection array is `[1,2,3,4,5]`
We decide to deactivate id 3. 3 has been added to pendingDeactivations and stakers will vote based on the above order.

Now the issue lies that after the id has been deactivated, we change the order in medians to facilitate the new order in activeCollection `[1,2,4,5]` but the staker's votes aren't changed. So at the time of giving penalties, when we call for the vote value of id 4, it points to wrong value in the staker's vote. It will point to the value of collection id 3 but that has been deactivated, there by giving out incorrect penalties.

@hrishikeshio @SkandaBhat @abhishekvispute
