### ISSUE TITLE
P+episilon attack can cause mass unstaking

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#606]

**Comment by hrishikeshio** [comment]
Issue:

Solve p+e attack and hit and run attack

p+e attack 
happens when attacker signals attack causing mass unstaking.
in PoS version this is not possible since there are no monetary penalties for incoherent reporting
after dispute resolution is implemented, this will become a serious issue.
Solution:
Have an unstake lock during which staker has to vote.

Hit and run attack
happens during the last round where staker is forced to participate
staker can report incorrect value and run.
solved by implementing withdraw lock. Since staker's stake is locked, it will be in their interest
to vote coherently and avoid razor price crash.

**Comment by hrishikeshio** [comment]
unstake -> lock srzr and participate
withdraw -> burn srzr and lock rzr and stop participate
withdraw2 -> transfer rzr
