### ISSUE TITLE
Testing Assign Collections/Assets Randomly

### ISSUE THREAD

**Issue by abhishekvispute** [razor-network/contracts#657]
To @GauravJain9 
Please Update followoing as per AAR all in this #649 PR
Fork my branch and make PR there

- [ ] BlockManager
- [ ] StakeManager
- [ ] VoteManager

To @abhishekvispute : Positive cases are already tested and another positive flows would be done by above

Following are neg cases we have to do

- [ ] Proposer dont reveal non assigned assets, 
- [ ] Proposer dont reveal assigned assets
- [ ] Staker uses gigantic merkle
- [ ] Dispute happens on non assigned asset of this epoch
- [ ] Delegator is able to fetch non assigned asset

**Comment by GauravJain9** [comment]
Test Cases Review (TBD) :

1) With this implementation, secret is fixed for everyone. This decreases the testing scope, as for everyone same assets would be assigned. First, make it such that, you accept secret as input parameter, and have seperate secret for each staker

2) Then for readability, commitment[1], 2 ,3 ,4 is very tough to track rather than that return the object from getCommitAndRevealData not a array we can do it something like this result.secret, result.voteValues.

3) Propose logic is repeated throughout out tests, to find medians move this to helper.

4) propose median calculation is not correct its working only because, same secret is being used for everyone looping through commitment[3].length won't work if their are diff secret.

5) Please write a test case, that it should revert if any of assigned revealed value is zero,
In VoteManager.

6) add that negative reveal case with reveal values as 0, specified above here https://github.com/razor-network/contracts/pull/649/files/43304d6ff4e423907331e4235b4b6df6d5847219#r800437590

7) Why is blockManager 2nd last test case commented.
