### ISSUE TITLE
Lock Mechanism Changes | As per experience from Incent Test Net 

### ISSUE THREAD

**Issue by abhishekvispute** [razor-network/contracts#736]
### Testnet

```
Unstake (amount in sRZRs)

sRZR to RZR conversion is done here only 
sRZR is burned 
And rzr is locked 

UnstakeLockPeriod
—— 
——
WithdrawReleasePerod

```

### Master

```
Unstake (amount in sRZRs)
Lock sRZR

UnstakeLockPeriod — p + e

———  InitiateWithdraw() - epoch + WithdrawLockPeriod

WithdrawInititationPeriod 

——— Missed - ``extendLock()``

WithdrawLockPeriod — Hit and Run

Withdraw()
```

## Things to do 

- [ ] Rename 
``extendLock()``  to ``resetWithdrawInitiationPeriod()``
- [ ] Have a feature to reset the unstake lock

**Comment by abhishekvispute** [comment]
Discuss if penalty mech is going to stop front -run lock mech

**Comment by SamAg19** [comment]
Regarding issue, we would need to penalize stakers if they reset their unstake locks due to the the front run unstake attack mentioned in the delegation of stake PR https://github.com/razor-network/contracts/pull/121

We can also look to change the way we give out extend unstake lock penalty by giving out the penalty the way we give for inactivity, i.e. after withdrawInitiationPeriod is over, the number of epoch he takes to then again extend lock * the extend lock penalty.  this is to avoid scenarios where a staker unstakes a large amount but does not initiateWithdraw until he performs the attack and then immediately withdraws, in turn facing a small penalty for extension for higher gains.
