### ISSUE TITLE
Upgrade elliptic version to >=6.5.4

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#82]
### Dependabot cannot update elliptic to a non-vulnerable version
The latest possible version that can be installed is 6.5.3 because of the following conflicting dependencies:

```
@nomiclabs/hardhat-truffle5@2.0.0 requires elliptic@6.5.3 via a transitive dependency on ethers@4.0.48
@nomiclabs/hardhat-truffle5@2.0.0 requires elliptic@6.5.3 via a transitive dependency on ethers@4.0.48
solidity-coverage@0.7.15 requires elliptic@6.5.3 via a transitive dependency on ethers@4.0.48
eth-gas-reporter@0.2.21 requires elliptic@6.5.3 via ethers@4.0.48
hardhat-gas-reporter@1.0.4 requires elliptic@6.5.3 via a transitive dependency on ethers@4.0.48
```
The earliest fixed version is 6.5.4.

**Comment by SkandaBhat** [comment]
### Remediation
Upgrade elliptic to version 6.5.4 or later. For example:

```
"dependencies": {
  "elliptic": ">=6.5.4"
}
```
or…
```
"devDependencies": {
  "elliptic": ">=6.5.4"
}
```
Always verify the validity and compatibility of suggestions with your codebase.

### Details
**CVE-2020-28498**
_moderate severity_
Vulnerable versions: < 6.5.4
Patched version: 6.5.4
The npm package elliptic before version 6.5.4 are vulnerable to Cryptographic Issues via the secp256k1 implementation in elliptic/ec/key.js. There is no check to confirm that the public key point passed into the derive function actually exists on the secp256k1 curve. This results in the potential for the private key used in this implementation to be revealed after a number of ECDH operations are performed.

**Comment by hrishikeshio** [comment]
Seems a small issue pending for a long time. @dev1644 can you resolve this?

**Comment by dev1644** [comment]
@hrishikeshio, I & @SkandaBhat already discussed it a few months back, I forgot to update the issue. Here's the conclusion from the investigation.

That security vulnerability is coming from dependencies, Caused by these dependencies -
- solidity-coverage
- hardhat-gas-reporter
- eth-gas-reporter (same as hardhat-gas-reporter) I have removed it.
- @nomiclabs/hardhat-truffle5

`solidity-coverage` generates coverage report so not an issue, same with `hardhat-gas-reporter`.
`hardhat-truffle5` is a plugin that we use to execute our tests so no harm here too.

I think it's not worth the effort since the issue is not severe and only is in dev tools.

**Comment by SkandaBhat** [comment]
Closing this issue. We have to wait till one of the dependencies is upgraded. Then, dependabot will automatically bump up the version.
