### ISSUE TITLE
Write a test for the last if in `isElectedProposer`

### ISSUE THREAD

**Issue by SamAg19** [razor-network/contracts#865]
https://github.com/razor-network/contracts/blob/5553b2cef7d0e0dba0f56c8dfcdf28f10bc216fc/contracts/Core/BlockManager.sol#L618

test it by looping multiple times

The branch is not covered. We need to add tests for this.

**Comment by rajkharvar** [comment]
`if (rand2 * (biggestStake) > stake * (2**32)) return (false); `
@SamAg19 I tried to test the above line with some insanely high iteration(1e48), but it returns false during first `if` statement because `if ((rand1 + 1) != stakerId)` get satisfied most of the time.

Second `if` condition can be tested only if we have biggestStake of order of `1e36`.
Shall we try to test it using that approach?
